name: Twitter Scraper

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:        # manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install specific version of Google Chrome
      run: |
        CHROME_DEB="google-chrome-stable_122.0.6261.111-1_amd64.deb"
        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/$CHROME_DEB
        sudo apt install -y ./$CHROME_DEB

    - name: Install matching ChromeDriver
      run: |
        VERSION="122.0.6261.111"
        wget https://chromedriver.storage.googleapis.com/${VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        chmod +x /usr/local/bin/chromedriver

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Twitter scraper
      env:
        TWITTER_EMAIL: ${{ secrets.TWITTER_EMAIL }}
        TWITTER_PASSWORD: ${{ secrets.TWITTER_PASSWORD }}
        TARGET_USERNAMES: ${{ secrets.TARGET_USERNAMES }}
      run: python x.py

    - name: Commit updates
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *_following.txt || true
        git commit -m "Update following list" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
