name: Twitter Following Scraper

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Twitter username (no @)'
        required: true
        default: 'shawmakesmagic'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        pip install selenium

    - name: Install Chrome + Chromedriver
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver

    - name: Run Scraper with Username
      run: python x.py ${{ github.event.inputs.username }}

    - name: Commit Results
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add ${{ github.event.inputs.username }}_following.txt
        git commit -m "Update following list for ${{ github.event.inputs.username }}" || echo "No changes to commit"
        git push
